"""

Revision ID: 1cb5547618a0
Revises: e38532aee2b8
Create Date: 2025-01-11 00:20:42.360650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb5547618a0'
down_revision = 'e38532aee2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=10), nullable=False))

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_column('media_type')

    with op.batch_alter_table('watched', schema=None) as batch_op:
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
