"""reset_migration

Revision ID: e38532aee2b8
Revises: fdeda873b8a1
Create Date: 2025-01-10 03:25:28.997534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38532aee2b8'
down_revision = 'fdeda873b8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_followed')
    with op.batch_alter_table('followed', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_followed', ['user_id', 'followed_user_id'])

    with op.batch_alter_table('imc_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_code', sa.String(length=65), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_imc_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_imc_user_previous_code'), ['previous_code'])

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_resident_door_number'), ['door_number'])
        batch_op.create_unique_constraint(batch_op.f('uq_resident_phone_number'), ['phone_number'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    with op.batch_alter_table('watched', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_watched_user_id'), ['user_id', 'movie_id'])

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_watchlist_user_id'), ['user_id', 'movie_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_watchlist_user_id'), type_='unique')

    with op.batch_alter_table('watched', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_watched_user_id'), type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_resident_phone_number'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_resident_door_number'), type_='unique')

    with op.batch_alter_table('imc_user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_imc_user_previous_code'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_imc_user_email'), type_='unique')
        batch_op.drop_column('previous_code')

    with op.batch_alter_table('followed', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_followed', type_='unique')

    op.create_table('_alembic_tmp_followed',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('followed_user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['imc_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('followed_user_id', name='uq_followed_followed_user_id')
    )
    # ### end Alembic commands ###
