"""Invitation_codes

Revision ID: fdeda873b8a1
Revises: f1780f1dbf4c
Create Date: 2025-01-10 03:05:04.684494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdeda873b8a1'
down_revision = 'f1780f1dbf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followed', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['followed_user_id'])

    with op.batch_alter_table('imc_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_code', sa.String(length=65), nullable=False))
        batch_op.create_unique_constraint(None, ['previous_code'])

    with op.batch_alter_table('watched', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['movie_id'])

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['movie_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('watched', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('imc_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('previous_code')

    with op.batch_alter_table('followed', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
